### ISSUE TITLE
Can you release corresponding names of the genera/families/orders annotations in CUB_200_2011?

### ISSUE THREAD

**Issue by xiapeng1110** [lvyilin/STrHCE#1]
Thanks for your great work. I'm doing some work on the hierarchical representation, and the corresponding name of the 122 genera, 37 families, and 13 orders annotations is very important to my work. Maybe is [`classes.txt` ](https://github.com/lvyilin/STrHCE/blob/master/datasets/cub2011hier2.py#L47). Can you release it? Thanks a lot.

**Comment by lvyilin** [comment]
This file is from the CUB_200_2011 dataset, and we did not use the name in our code. Perhaps you can find the name of the hierarchical category [here](https://arxiv.org/pdf/1808.04505.pdf) or just cut from the class name. Hope this may help you.
